// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VSN
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerInfo : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PlayerInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint PlayerUid { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint PlayerCharacterTid { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<VSN.PlayerInfo> CreatePlayerInfo(FlatBufferBuilder builder, uint PlayerUid, uint PlayerCharacterTid) {
    builder.Prep(4, 8);
    builder.PutUint(PlayerCharacterTid);
    builder.PutUint(PlayerUid);
    return new Offset<VSN.PlayerInfo>(builder.Offset);
  }
}


}
