// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VSN
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WebGameInfoData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static WebGameInfoData GetRootAsWebGameInfoData(ByteBuffer _bb) { return GetRootAsWebGameInfoData(_bb, new WebGameInfoData()); }
  public static WebGameInfoData GetRootAsWebGameInfoData(ByteBuffer _bb, WebGameInfoData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyWebGameInfoData(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, WebGameInfoDataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WebGameInfoData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint GameId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint MapTypeId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Difficulty { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public uint SpawnableItems(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int SpawnableItemsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetSpawnableItemsBytes() { return __p.__vector_as_span<uint>(10, 4); }
#else
  public ArraySegment<byte>? GetSpawnableItemsBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public uint[] GetSpawnableItemsArray() { return __p.__vector_as_array<uint>(10); }
  public uint PlayerAccountId(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int PlayerAccountIdLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetPlayerAccountIdBytes() { return __p.__vector_as_span<uint>(12, 4); }
#else
  public ArraySegment<byte>? GetPlayerAccountIdBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public uint[] GetPlayerAccountIdArray() { return __p.__vector_as_array<uint>(12); }
  public uint PlayerCharacterType(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int PlayerCharacterTypeLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetPlayerCharacterTypeBytes() { return __p.__vector_as_span<uint>(14, 4); }
#else
  public ArraySegment<byte>? GetPlayerCharacterTypeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public uint[] GetPlayerCharacterTypeArray() { return __p.__vector_as_array<uint>(14); }
  public string PlayerAuthToken(int j) { int o = __p.__offset(16); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int PlayerAuthTokenLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<VSN.WebGameInfoData> CreateWebGameInfoData(FlatBufferBuilder builder,
      uint game_id = 0,
      uint map_type_id = 0,
      byte difficulty = 0,
      VectorOffset spawnable_itemsOffset = default(VectorOffset),
      VectorOffset player_account_idOffset = default(VectorOffset),
      VectorOffset player_character_typeOffset = default(VectorOffset),
      VectorOffset player_auth_tokenOffset = default(VectorOffset)) {
    builder.StartTable(7);
    WebGameInfoData.AddPlayerAuthToken(builder, player_auth_tokenOffset);
    WebGameInfoData.AddPlayerCharacterType(builder, player_character_typeOffset);
    WebGameInfoData.AddPlayerAccountId(builder, player_account_idOffset);
    WebGameInfoData.AddSpawnableItems(builder, spawnable_itemsOffset);
    WebGameInfoData.AddMapTypeId(builder, map_type_id);
    WebGameInfoData.AddGameId(builder, game_id);
    WebGameInfoData.AddDifficulty(builder, difficulty);
    return WebGameInfoData.EndWebGameInfoData(builder);
  }

  public static void StartWebGameInfoData(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddGameId(FlatBufferBuilder builder, uint gameId) { builder.AddUint(0, gameId, 0); }
  public static void AddMapTypeId(FlatBufferBuilder builder, uint mapTypeId) { builder.AddUint(1, mapTypeId, 0); }
  public static void AddDifficulty(FlatBufferBuilder builder, byte difficulty) { builder.AddByte(2, difficulty, 0); }
  public static void AddSpawnableItems(FlatBufferBuilder builder, VectorOffset spawnableItemsOffset) { builder.AddOffset(3, spawnableItemsOffset.Value, 0); }
  public static VectorOffset CreateSpawnableItemsVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateSpawnableItemsVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSpawnableItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSpawnableItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSpawnableItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPlayerAccountId(FlatBufferBuilder builder, VectorOffset playerAccountIdOffset) { builder.AddOffset(4, playerAccountIdOffset.Value, 0); }
  public static VectorOffset CreatePlayerAccountIdVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAccountIdVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAccountIdVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAccountIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPlayerAccountIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPlayerCharacterType(FlatBufferBuilder builder, VectorOffset playerCharacterTypeOffset) { builder.AddOffset(5, playerCharacterTypeOffset.Value, 0); }
  public static VectorOffset CreatePlayerCharacterTypeVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePlayerCharacterTypeVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerCharacterTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerCharacterTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPlayerCharacterTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPlayerAuthToken(FlatBufferBuilder builder, VectorOffset playerAuthTokenOffset) { builder.AddOffset(6, playerAuthTokenOffset.Value, 0); }
  public static VectorOffset CreatePlayerAuthTokenVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAuthTokenVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAuthTokenVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayerAuthTokenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPlayerAuthTokenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<VSN.WebGameInfoData> EndWebGameInfoData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VSN.WebGameInfoData>(o);
  }
  public static void FinishWebGameInfoDataBuffer(FlatBufferBuilder builder, Offset<VSN.WebGameInfoData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedWebGameInfoDataBuffer(FlatBufferBuilder builder, Offset<VSN.WebGameInfoData> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class WebGameInfoDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*GameId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*MapTypeId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Difficulty*/, 1 /*byte*/, 1, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*SpawnableItems*/, 4 /*uint*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*PlayerAccountId*/, 4 /*uint*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*PlayerCharacterType*/, 4 /*uint*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 16 /*PlayerAuthToken*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
