// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTERSTATE_VSN_H_
#define FLATBUFFERS_GENERATED_MONSTERSTATE_VSN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

#include "Types_generated.h"

namespace VSN {

struct MonsterStateInfo;

struct MonsterStates;
struct MonsterStatesBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MonsterStateInfo FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t nid_;
  uint8_t state_;
  int8_t padding0__;  int16_t padding1__;
  VSN::Vector2 pos_;
  uint8_t left_;
  int8_t padding2__;  int16_t padding3__;

 public:
  MonsterStateInfo()
      : nid_(0),
        state_(0),
        padding0__(0),
        padding1__(0),
        pos_(),
        left_(0),
        padding2__(0),
        padding3__(0) {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
    (void)padding3__;
  }
  MonsterStateInfo(uint32_t _nid, uint8_t _state, const VSN::Vector2 &_pos, bool _left)
      : nid_(::flatbuffers::EndianScalar(_nid)),
        state_(::flatbuffers::EndianScalar(_state)),
        padding0__(0),
        padding1__(0),
        pos_(_pos),
        left_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_left))),
        padding2__(0),
        padding3__(0) {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
    (void)padding3__;
  }
  uint32_t nid() const {
    return ::flatbuffers::EndianScalar(nid_);
  }
  uint8_t state() const {
    return ::flatbuffers::EndianScalar(state_);
  }
  const VSN::Vector2 &pos() const {
    return pos_;
  }
  bool left() const {
    return ::flatbuffers::EndianScalar(left_) != 0;
  }
};
FLATBUFFERS_STRUCT_END(MonsterStateInfo, 20);

struct MonsterStates FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MonsterStatesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INFOS = 4
  };
  const ::flatbuffers::Vector<const VSN::MonsterStateInfo *> *infos() const {
    return GetPointer<const ::flatbuffers::Vector<const VSN::MonsterStateInfo *> *>(VT_INFOS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INFOS) &&
           verifier.VerifyVector(infos()) &&
           verifier.EndTable();
  }
};

struct MonsterStatesBuilder {
  typedef MonsterStates Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_infos(::flatbuffers::Offset<::flatbuffers::Vector<const VSN::MonsterStateInfo *>> infos) {
    fbb_.AddOffset(MonsterStates::VT_INFOS, infos);
  }
  explicit MonsterStatesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MonsterStates> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MonsterStates>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MonsterStates> CreateMonsterStates(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const VSN::MonsterStateInfo *>> infos = 0) {
  MonsterStatesBuilder builder_(_fbb);
  builder_.add_infos(infos);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MonsterStates> CreateMonsterStatesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<VSN::MonsterStateInfo> *infos = nullptr) {
  auto infos__ = infos ? _fbb.CreateVectorOfStructs<VSN::MonsterStateInfo>(*infos) : 0;
  return VSN::CreateMonsterStates(
      _fbb,
      infos__);
}

inline const VSN::MonsterStates *GetMonsterStates(const void *buf) {
  return ::flatbuffers::GetRoot<VSN::MonsterStates>(buf);
}

inline const VSN::MonsterStates *GetSizePrefixedMonsterStates(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSN::MonsterStates>(buf);
}

inline bool VerifyMonsterStatesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSN::MonsterStates>(nullptr);
}

inline bool VerifySizePrefixedMonsterStatesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSN::MonsterStates>(nullptr);
}

inline void FinishMonsterStatesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::MonsterStates> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonsterStatesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::MonsterStates> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSN

#endif  // FLATBUFFERS_GENERATED_MONSTERSTATE_VSN_H_
