// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTERDAMAGED_VSN_H_
#define FLATBUFFERS_GENERATED_MONSTERDAMAGED_VSN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

#include "Types_generated.h"

namespace VSN {

struct DamagedMonsterInfo;

struct MonsterDamaged;
struct MonsterDamagedBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) DamagedMonsterInfo FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t nid_;
  int16_t damage_;
  uint8_t dead_;
  int8_t padding0__;

 public:
  DamagedMonsterInfo()
      : nid_(0),
        damage_(0),
        dead_(0),
        padding0__(0) {
    (void)padding0__;
  }
  DamagedMonsterInfo(uint32_t _nid, int16_t _damage, bool _dead)
      : nid_(::flatbuffers::EndianScalar(_nid)),
        damage_(::flatbuffers::EndianScalar(_damage)),
        dead_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_dead))),
        padding0__(0) {
    (void)padding0__;
  }
  uint32_t nid() const {
    return ::flatbuffers::EndianScalar(nid_);
  }
  int16_t damage() const {
    return ::flatbuffers::EndianScalar(damage_);
  }
  bool dead() const {
    return ::flatbuffers::EndianScalar(dead_) != 0;
  }
};
FLATBUFFERS_STRUCT_END(DamagedMonsterInfo, 8);

struct MonsterDamaged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MonsterDamagedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INFOS = 4
  };
  const ::flatbuffers::Vector<const VSN::DamagedMonsterInfo *> *infos() const {
    return GetPointer<const ::flatbuffers::Vector<const VSN::DamagedMonsterInfo *> *>(VT_INFOS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INFOS) &&
           verifier.VerifyVector(infos()) &&
           verifier.EndTable();
  }
};

struct MonsterDamagedBuilder {
  typedef MonsterDamaged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_infos(::flatbuffers::Offset<::flatbuffers::Vector<const VSN::DamagedMonsterInfo *>> infos) {
    fbb_.AddOffset(MonsterDamaged::VT_INFOS, infos);
  }
  explicit MonsterDamagedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MonsterDamaged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MonsterDamaged>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MonsterDamaged> CreateMonsterDamaged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const VSN::DamagedMonsterInfo *>> infos = 0) {
  MonsterDamagedBuilder builder_(_fbb);
  builder_.add_infos(infos);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MonsterDamaged> CreateMonsterDamagedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<VSN::DamagedMonsterInfo> *infos = nullptr) {
  auto infos__ = infos ? _fbb.CreateVectorOfStructs<VSN::DamagedMonsterInfo>(*infos) : 0;
  return VSN::CreateMonsterDamaged(
      _fbb,
      infos__);
}

inline const VSN::MonsterDamaged *GetMonsterDamaged(const void *buf) {
  return ::flatbuffers::GetRoot<VSN::MonsterDamaged>(buf);
}

inline const VSN::MonsterDamaged *GetSizePrefixedMonsterDamaged(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSN::MonsterDamaged>(buf);
}

inline bool VerifyMonsterDamagedBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSN::MonsterDamaged>(nullptr);
}

inline bool VerifySizePrefixedMonsterDamagedBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSN::MonsterDamaged>(nullptr);
}

inline void FinishMonsterDamagedBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::MonsterDamaged> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonsterDamagedBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::MonsterDamaged> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSN

#endif  // FLATBUFFERS_GENERATED_MONSTERDAMAGED_VSN_H_
