// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERDAMAGED_VSN_H_
#define FLATBUFFERS_GENERATED_PLAYERDAMAGED_VSN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

namespace VSN {

struct PlayerDamaged;
struct PlayerDamagedBuilder;

struct PlayerDamaged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerDamagedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_DAMAGE = 6
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  int32_t damage() const {
    return GetField<int32_t>(VT_DAMAGE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_DAMAGE, 4) &&
           verifier.EndTable();
  }
};

struct PlayerDamagedBuilder {
  typedef PlayerDamaged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(PlayerDamaged::VT_PLAYER_ID, player_id, 0);
  }
  void add_damage(int32_t damage) {
    fbb_.AddElement<int32_t>(PlayerDamaged::VT_DAMAGE, damage, 0);
  }
  explicit PlayerDamagedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerDamaged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerDamaged>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerDamaged> CreatePlayerDamaged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    int32_t damage = 0) {
  PlayerDamagedBuilder builder_(_fbb);
  builder_.add_damage(damage);
  builder_.add_player_id(player_id);
  return builder_.Finish();
}

inline const VSN::PlayerDamaged *GetPlayerDamaged(const void *buf) {
  return ::flatbuffers::GetRoot<VSN::PlayerDamaged>(buf);
}

inline const VSN::PlayerDamaged *GetSizePrefixedPlayerDamaged(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSN::PlayerDamaged>(buf);
}

inline bool VerifyPlayerDamagedBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSN::PlayerDamaged>(nullptr);
}

inline bool VerifySizePrefixedPlayerDamagedBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSN::PlayerDamaged>(nullptr);
}

inline void FinishPlayerDamagedBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::PlayerDamaged> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerDamagedBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::PlayerDamaged> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSN

#endif  // FLATBUFFERS_GENERATED_PLAYERDAMAGED_VSN_H_
