// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERLEVELUP_VSN_H_
#define FLATBUFFERS_GENERATED_PLAYERLEVELUP_VSN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

namespace VSN {

struct PlayerLevelUp;
struct PlayerLevelUpBuilder;

struct PlayerLevelUp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerLevelUpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_NOW_LEVEL = 6
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint16_t now_level() const {
    return GetField<uint16_t>(VT_NOW_LEVEL, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint16_t>(verifier, VT_NOW_LEVEL, 2) &&
           verifier.EndTable();
  }
};

struct PlayerLevelUpBuilder {
  typedef PlayerLevelUp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(PlayerLevelUp::VT_PLAYER_ID, player_id, 0);
  }
  void add_now_level(uint16_t now_level) {
    fbb_.AddElement<uint16_t>(PlayerLevelUp::VT_NOW_LEVEL, now_level, 0);
  }
  explicit PlayerLevelUpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerLevelUp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerLevelUp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerLevelUp> CreatePlayerLevelUp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint16_t now_level = 0) {
  PlayerLevelUpBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_now_level(now_level);
  return builder_.Finish();
}

inline const VSN::PlayerLevelUp *GetPlayerLevelUp(const void *buf) {
  return ::flatbuffers::GetRoot<VSN::PlayerLevelUp>(buf);
}

inline const VSN::PlayerLevelUp *GetSizePrefixedPlayerLevelUp(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSN::PlayerLevelUp>(buf);
}

inline bool VerifyPlayerLevelUpBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSN::PlayerLevelUp>(nullptr);
}

inline bool VerifySizePrefixedPlayerLevelUpBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSN::PlayerLevelUp>(nullptr);
}

inline void FinishPlayerLevelUpBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::PlayerLevelUp> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerLevelUpBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::PlayerLevelUp> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSN

#endif  // FLATBUFFERS_GENERATED_PLAYERLEVELUP_VSN_H_
