// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REQGETEXP_VSN_H_
#define FLATBUFFERS_GENERATED_REQGETEXP_VSN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

namespace VSN {

struct Req_GetExp;
struct Req_GetExpBuilder;

struct Req_GetExp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Req_GetExpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_ID = 4,
    VT_EXP_ITEM_ID = 6
  };
  uint32_t req_id() const {
    return GetField<uint32_t>(VT_REQ_ID, 0);
  }
  uint32_t exp_item_id() const {
    return GetField<uint32_t>(VT_EXP_ITEM_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_EXP_ITEM_ID, 4) &&
           verifier.EndTable();
  }
};

struct Req_GetExpBuilder {
  typedef Req_GetExp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_id(uint32_t req_id) {
    fbb_.AddElement<uint32_t>(Req_GetExp::VT_REQ_ID, req_id, 0);
  }
  void add_exp_item_id(uint32_t exp_item_id) {
    fbb_.AddElement<uint32_t>(Req_GetExp::VT_EXP_ITEM_ID, exp_item_id, 0);
  }
  explicit Req_GetExpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Req_GetExp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Req_GetExp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Req_GetExp> CreateReq_GetExp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    uint32_t exp_item_id = 0) {
  Req_GetExpBuilder builder_(_fbb);
  builder_.add_exp_item_id(exp_item_id);
  builder_.add_req_id(req_id);
  return builder_.Finish();
}

inline const VSN::Req_GetExp *GetReq_GetExp(const void *buf) {
  return ::flatbuffers::GetRoot<VSN::Req_GetExp>(buf);
}

inline const VSN::Req_GetExp *GetSizePrefixedReq_GetExp(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VSN::Req_GetExp>(buf);
}

inline bool VerifyReq_GetExpBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VSN::Req_GetExp>(nullptr);
}

inline bool VerifySizePrefixedReq_GetExpBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VSN::Req_GetExp>(nullptr);
}

inline void FinishReq_GetExpBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::Req_GetExp> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedReq_GetExpBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VSN::Req_GetExp> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VSN

#endif  // FLATBUFFERS_GENERATED_REQGETEXP_VSN_H_
