#pragma once

#include "packet/WebGameInfo_generated.h"
#include "packet/ConnectGame_generated.h"
#include "packet/GameLoadInfo_generated.h"
#include "packet/CountDown_generated.h"
#include "packet/ItemSpawn_generated.h"
#include "packet/MonsterDamaged_generated.h"
#include "packet/MonsterDead_generated.h"
#include "packet/MonsterSpawn_generated.h"
#include "packet/MonsterState_generated.h"
#include "packet/PlayerDamaged_generated.h"
#include "packet/PlayerLevelUp_generated.h"
#include "packet/PlayerGetItem_generated.h"
#include "packet/PlayerState_generated.h"
#include "packet/PlayerUpgrade_generated.h"
#include "packet/Response_generated.h"
#include "packet/Types_generated.h"
#include "packet/Req_GetExp_generated.h"
#include "packet/Req_GetItem_generated.h"
#include "packet/Req_MonsterDamaged_generated.h"
#include "packet/Req_PlayerDamaged_generated.h"
#include "packet/Res_GetExp_generated.h"
#include "packet/SimplePacket_generated.h"

#include "data/MapData_generated.h"

